# Generated by Django 6.0.6 on 2026-06-26 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confederacion_territorial', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Debe ser de 2 dígitos.')])),
                ('federacion_local', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Debe ser de 5 dígitos.')])),
                ('federacion_sectorial', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Debe ser de 2 dígitos.')])),
                ('sindicato_codigo', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe ser de 3 dígitos.')])),
                ('num_afiliado', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Debe ser de 6 dígitos.')])),
                ('nombre_apellidos', models.CharField(max_length=255)),
                ('lengua', models.CharField(choices=[('A', 'Castellano'), ('C', 'Catalán')], max_length=1)),
                ('estado', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=4)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('notas_historicas', models.TextField(blank=True, help_text='Registro de reemisiones históricas.', null=True)),
                ('sindicato_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuerdo_aceptado', models.BooleanField(default=False, verbose_name='¿Ha aceptado el acuerdo de protección de datos?')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la firma')),
                ('ip_aceptacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP de la firma')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
