# Generated by Django 5.2.17 on 2026-08-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="afiliado",
            name="estado_impresion",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de imprimir"),
                    ("IMPRESO", "Impreso"),
                ],
                default="PENDIENTE",
                max_length=10,
                verbose_name="Estado de impresión",
            ),
        ),
        migrations.AddField(
            model_name="afiliado",
            name="fecha_envio_imprenta",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de envío a imprenta"
            ),
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.CharField(max_length=500)),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
