# Generated by Django 5.2.17 on 2026-08-06 12:40

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_afiliado_estado_impresion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="afiliado",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalAfiliado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "confederacion_territorial",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Debe ser de 2 dígitos."
                            )
                        ],
                    ),
                ),
                (
                    "federacion_local",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{5}$", "Debe ser de 5 dígitos."
                            )
                        ],
                    ),
                ),
                (
                    "federacion_sectorial",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Debe ser de 2 dígitos."
                            )
                        ],
                    ),
                ),
                (
                    "sindicato_codigo",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}$", "Debe ser de 3 dígitos."
                            )
                        ],
                    ),
                ),
                (
                    "num_afiliado",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6}$", "Debe ser de 6 dígitos."
                            )
                        ],
                    ),
                ),
                ("nombre_apellidos", models.CharField(max_length=255)),
                (
                    "lengua",
                    models.CharField(
                        choices=[("A", "Castellano"), ("C", "Catalán")], max_length=1
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ALTA", "Alta"), ("BAJA", "Baja")], max_length=4
                    ),
                ),
                ("fecha_expedicion", models.DateField(blank=True, null=True)),
                (
                    "notas_historicas",
                    models.TextField(
                        blank=True,
                        help_text="Registro de reemisiones históricas.",
                        null=True,
                    ),
                ),
                (
                    "estado_impresion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de imprimir"),
                            ("IMPRESO", "Impreso"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado de impresión",
                    ),
                ),
                (
                    "fecha_envio_imprenta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío a imprenta"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sindicato_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical afiliado",
                "verbose_name_plural": "historical afiliados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RegistroSubida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cantidad_afiliados", models.IntegerField()),
                ("nombre_archivo", models.CharField(max_length=255)),
                (
                    "sindicato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
