# Generated by Django 5.2.15 on 2026-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_registrosubida"),
    ]

    operations = [
        migrations.AddField(
            model_name="afiliado",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalafiliado",
            name="fecha_creacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="afiliado",
            name="estado",
            field=models.CharField(
                choices=[("ALTA", "Alta"), ("BAJA", "Baja")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalafiliado",
            name="estado",
            field=models.CharField(
                choices=[("ALTA", "Alta"), ("BAJA", "Baja")], max_length=50
            ),
        ),
    ]
