# Generated by Django 5.2.17 on 2026-08-21 12:27

import django.core.validators
import gestion.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_afiliado_estado_impresion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='nombre_apellidos',
            field=gestion.crypto.CampoTextoCifrado(max_length=255),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='notas_historicas',
            field=gestion.crypto.CampoTextoCifrado(blank=True, help_text='Registro de reemisiones históricas.', null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='num_afiliado',
            field=gestion.crypto.CampoTextoCifrado(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Debe ser de 6 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='historicalafiliado',
            name='nombre_apellidos',
            field=gestion.crypto.CampoTextoCifrado(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalafiliado',
            name='notas_historicas',
            field=gestion.crypto.CampoTextoCifrado(blank=True, help_text='Registro de reemisiones históricas.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalafiliado',
            name='num_afiliado',
            field=gestion.crypto.CampoTextoCifrado(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Debe ser de 6 dígitos.')]),
        ),
    ]
