# Generated by Django 5.2.17 on 2026-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_depurar_datos_personales_del_log_del_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilsindicato',
            name='nombre_identificativo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sindicato o rama que declara ser (para aprobar el alta)'),
        ),
    ]
