# Generated by Django 5.2.17 on 2026-08-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_perfilsindicato_nombre_identificativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Se rellena sola al pasar a BAJA. Desde aquí corre el plazo de conservación.', null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='historicalafiliado',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Se rellena sola al pasar a BAJA. Desde aquí corre el plazo de conservación.', null=True, verbose_name='Fecha de baja'),
        ),
    ]
