# Generated by Django 5.2.17 on 2026-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_afiliado_fecha_baja_historicalafiliado_fecha_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilsindicato',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Persona que solicita el alta'),
        ),
    ]
