# Generated by Django 5.2.17 on 2026-08-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_perfilsindicato_persona_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'notificación', 'verbose_name_plural': 'notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='perfilsindicato',
            options={'verbose_name': 'sindicato', 'verbose_name_plural': 'sindicatos'},
        ),
        migrations.AlterModelOptions(
            name='registrosubida',
            options={'verbose_name': 'carga de afiliados', 'verbose_name_plural': 'cargas de afiliados'},
        ),
    ]
