"""
Django settings for sistema_carnets project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables definidas en el archivo .env de la raíz del repositorio.
# El archivo .env nunca se sube al repositorio (ver .gitignore); .env.example
# documenta las variables necesarias.
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# DEBUG debe estar desactivado en producción para no filtrar código fuente en caso de error.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Lista de hosts autorizados, separados por comas en la variable de entorno ALLOWED_HOSTS.
_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]


# --- Cifrado en reposo de los datos personales del afiliado (RGPD Art. 9) ---
#
# De dónde salen las claves lo decide el proveedor: la ruta de un invocable que
# devuelve "id:clave_base64,id:clave_base64" (la primera es la que cifra; las
# demás solo permiten leer lo guardado antes de la última rotación).
#
# Por defecto se leen del .env, que sirve para desarrollo local pero NO para
# datos reales: en producción deben custodiarse en un KMS/HSM. Cambiar de uno a
# otro es cambiar esta variable. Implementaciones copiables para AWS KMS, Azure
# Key Vault y HashiCorp Vault en deploy/claves_y_kms.md.
CARNETS_KEY_PROVIDER = os.environ.get(
    'CARNETS_KEY_PROVIDER', 'gestion.crypto.proveedor_desde_entorno',
)

# Solo lo usa el proveedor por defecto (el del entorno).
CARNETS_ENCRYPTION_KEYS = os.environ.get('CARNETS_ENCRYPTION_KEYS', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simple_history',
    # Segundo factor del admin. La cuenta de administrador es la unica que ve
    # los datos personales descifrados, asi que una contrasena robada entregaria
    # el archivo entero de afiliacion; ver gestion/admin.py.
    'django_otp',
    'django_otp.plugins.otp_totp',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Rechaza pronto (413) peticiones cuyo Content-Length declarado sea
    # excesivo, antes de que el resto del stack llegue a leer el cuerpo.
    'gestion.middleware.LimiteTamanoPeticionMiddleware',
    # Content-Security-Policy en todas las respuestas. Ver middleware.py.
    'gestion.middleware.CabeceraCSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Justo despues del de autenticacion, que es de quien depende: anade
    # request.user.is_verified() para saber si ademas de identificarse ha
    # pasado el segundo factor.
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'sistema_carnets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_carnets.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_ENGINE', 'sqlite3') == 'postgresql':
    # PostgreSQL en subred privada. La conexión sale del servidor de
    # aplicación y cruza la red hasta la base de datos, así que va cifrada
    # obligatoriamente: 'verify-full' además comprueba que el servidor al otro
    # lado es realmente el nuestro y no alguien interponiéndose. Bajarlo a
    # 'require' cifra pero deja la puerta abierta a un intermediario.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DATABASE_NAME'],
            'USER': os.environ['DATABASE_USER'],
            'PASSWORD': os.environ['DATABASE_PASSWORD'],
            'HOST': os.environ['DATABASE_HOST'],
            'PORT': os.environ.get('DATABASE_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DATABASE_CONN_MAX_AGE', '60')),
            'OPTIONS': {
                'sslmode': os.environ.get('DATABASE_SSLMODE', 'verify-full'),
                'sslrootcert': os.environ.get('DATABASE_SSLROOTCERT', ''),
            },
        },
    }
    # Sin certificado raíz, 'verify-full' no puede validar nada y psycopg
    # fallaría con un error poco claro: mejor decirlo aquí.
    if (
        DATABASES['default']['OPTIONS']['sslmode'].startswith('verify')
        and not DATABASES['default']['OPTIONS']['sslrootcert']
    ):
        raise ImproperlyConfigured(
            "DATABASE_SSLMODE=verify-* necesita DATABASE_SSLROOTCERT con la ruta "
            "del certificado raíz que firma el del servidor de base de datos.",
        )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # DATABASE_NAME permite apuntar a una BD aislada (p. ej. para las
            # pruebas dinámicas de tests/test_pentest.py contra un servidor real
            # sin tocar la base de datos de desarrollo). Por defecto, sin
            # cambios: db.sqlite3 en la carpeta del proyecto.
            'NAME': os.environ.get('DATABASE_NAME', str(BASE_DIR / 'db.sqlite3')),
        },
    }


# Caché
#
# Aquí la caché no es un detalle de rendimiento sino un control de seguridad:
# los limitadores de intentos de login (gestion/auth_views.py) y de alta de
# sindicatos (gestion/views.py) guardan su contador en ella. Con el backend por
# defecto de Django —memoria del proceso— cada worker de gunicorn lleva su
# propia cuenta, así que el límite de 5 intentos pasa a ser 5 por worker y se
# reinicia en cada recarga: deja de proteger sin que nada falle.
#
# En local, con un solo proceso, la memoria vale. En producción hace falta una
# caché compartida entre workers; lo comprueba gestion/checks.py al ejecutar
# `manage.py check --deploy`, que es lo que corre el script de despliegue.
CACHES = {
    'default': {
        'BACKEND': os.environ.get(
            'CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache',
        ),
        'LOCATION': os.environ.get('CACHE_LOCATION', ''),
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# La aplicación es íntegramente en español y sus usuarios (sindicatos) operan
# en España: el admin de Django y los mensajes se muestran en español y las
# fechas en el huso peninsular. Con USE_TZ=True el almacenamiento sigue en UTC;
# solo cambia la presentación. Ambos son sobreescribibles por entorno.
LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'es-es')

TIME_ZONE = os.environ.get('TIME_ZONE', 'Europe/Madrid')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'subir_excel'

# Coincide con el tipo real usado en las migraciones existentes de producción
# (AutoField, no BigAutoField: ver gestion/migrations/0002_...).
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Cookies de sesión/CSRF solo por HTTPS. Por defecto False para poder probar
# en local por HTTP; en producción (servida por HTTPS) debe ponerse a True
# en el .env del servidor.
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'

# Redirige HTTP -> HTTPS. Falso por defecto para poder probar en local sin
# certificado; en el .env del servidor de producción debe ponerse a True.
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'

# Detrás de un proxy que termina el TLS (nginx, el de PythonAnywhere), Django
# recibe la petición por HTTP y, sin esto, SECURE_SSL_REDIRECT la redirige a
# HTTPS una y otra vez: bucle de redirecciones y sitio caído. La cabecera dice
# cómo reconocer que el proxy ya sirvió por HTTPS.
#
# Solo debe activarse si el proxy REESCRIBE esa cabecera siempre. Si la deja
# pasar tal cual viene del cliente, cualquiera puede enviar
# X-Forwarded-Proto: https y hacer creer a Django que su conexión en claro era
# segura, con lo que las cookies marcadas como Secure viajarían por HTTP.
_proxy_ssl = os.environ.get('SECURE_PROXY_SSL_HEADER', '')
if _proxy_ssl:
    _cabecera, _, _valor = _proxy_ssl.partition(':')
    if not _valor:
        raise ImproperlyConfigured(
            "SECURE_PROXY_SSL_HEADER debe tener la forma "
            "'HTTP_X_FORWARDED_PROTO:https' (cabecera:valor esperado).",
        )
    SECURE_PROXY_SSL_HEADER = (_cabecera.strip(), _valor.strip())

# HSTS (HTTP Strict Transport Security): indica al navegador que use siempre
# HTTPS para este dominio. Se deja en 0 (desactivado) por defecto para poder
# probar en local por HTTP; en el .env del servidor HTTPS debe ponerse un valor
# alto (p. ej. 31536000 = 1 año). Cuando se activa, cubre también subdominios y
# habilita el preload, cerrando la ventana del primer acceso por HTTP.
# Activar HSTS sin servir todo por HTTPS deja el sitio inaccesible: hacerlo solo
# cuando el certificado esté en producción.
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
)
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True') == 'True'

# Evita el MIME sniffing del navegador (cabecera X-Content-Type-Options:nosniff),
# un vector para que un archivo subido se interprete como HTML/JS ejecutable.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Cierre de sesión automático por inactividad (RGPD).
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '1800'))
SESSION_EXPIRE_AT_BROWSER_CLOSE = (
    os.environ.get('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'True') == 'True'
)

LOGOUT_REDIRECT_URL = 'login'

# Configuración de email. Sin EMAIL_HOST definido, Django usa la consola
# (backend por defecto para desarrollo local, no envía correos reales).
# --- Registro de auditoría de accesos a datos personales (RGPD Art. 30) ---
#
# Los registros salen ya con formato JSON por el logger 'auditoria' (uno por
# línea), pensados para que un recolector los envíe a un destino externo de
# solo-adición. Un archivo en el propio servidor lo puede editar quien tenga
# acceso a él, así que por sí solo NO sirve como prueba ante una inspección:
# es el primer escalón, no el destino final. Ver deploy/auditoria_centralizada.md.
#
# Con AUDITORIA_LOG_PATH sin definir, los registros solo van a la salida
# estándar (lo normal en desarrollo y en las pruebas).
AUDITORIA_LOG_PATH = os.environ.get('AUDITORIA_LOG_PATH', '')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # El mensaje ya es un JSON completo: no se le añade nada que rompa el
        # formato para quien lo procese luego.
        'crudo': {'format': '%(message)s'},
    },
    'handlers': {
        'consola_auditoria': {
            'class': 'logging.StreamHandler',
            'formatter': 'crudo',
        },
    },
    'loggers': {
        'auditoria': {
            'handlers': ['consola_auditoria'],
            'level': 'INFO',
        },
    },
}

def preparar_destino_auditoria(ruta: str) -> None:
    """Crea la carpeta donde se escribirá el registro de auditoría.

    Si no se puede, la aplicación no arranca, y eso es lo correcto: sin
    registro de accesos no debe prestarse el servicio. Pero el error tiene que
    decir **qué variable** lo provoca. El fallo natural de `mkdir` es un
    `PermissionError` sobre una ruta suelta, a doce niveles de traza, y hay que
    llegar hasta este archivo para deducir de dónde sale. Pasó al desplegar: la
    ruta llevaba el nombre del directorio del proyecto en vez del del usuario.
    """
    try:
        Path(ruta).parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise ImproperlyConfigured(
            f"No se puede preparar la carpeta del registro de auditoría: {exc}. "
            f"Revisa AUDITORIA_LOG_PATH en el .env, que ahora vale {ruta!r}. "
            "Tiene que ser la ruta de un archivo dentro de una carpeta en la "
            "que este usuario pueda escribir (por ejemplo "
            "/home/TU_USUARIO/auditoria.jsonl, con TU_USUARIO y no el nombre "
            "del directorio del proyecto).",
        ) from exc


if AUDITORIA_LOG_PATH:
    preparar_destino_auditoria(AUDITORIA_LOG_PATH)
    LOGGING['handlers']['archivo_auditoria'] = {
        'class': 'logging.handlers.WatchedFileHandler',
        'filename': AUDITORIA_LOG_PATH,
        'formatter': 'crudo',
        # WatchedFileHandler (y no RotatingFileHandler) para que la rotación la
        # haga logrotate: así el archivo puede ser de solo-adición (chattr +a)
        # y ni siquiera el proceso de la aplicación puede reescribir lo ya escrito.
    }
    LOGGING['loggers']['auditoria']['handlers'].append('archivo_auditoria')

EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
